Fixes functions not rendered during markdown generation and no "find_module" AttributeError
Caused by modules not correctly loaded into namespace from commit due to Issue #57.
Modules now correctly loaded into namespace.
Fixes AttributeError("'FileFinder' object has no attribute 'find_module'") (#69)
Prioritized "find_spec" and falls back to "find_module" from loader if find_spec not available.
Some whitespace removal.