Docstring markdown render overhaul (preserves markdown syntax), new features and bugfixes including no find_module AttributeError fix (#85)
* Revert workaround as sync-label bug was fixed in labeler-v5.0.0

* Updated missing documentation for mdx support

* Fixes functions not rendered during markdown generation and no "find_module" AttributeError

Caused by modules not correctly loaded into namespace from commit due to Issue #57.
Modules now correctly loaded into namespace.
Fixes AttributeError("'FileFinder' object has no attribute 'find_module'") (#69)
Prioritized "find_spec" and falls back to "find_module" from loader if find_spec not available.
Some whitespace removal.

* Overhauled docstring render and added Github flavour admonition support

Modify argument regex
Fix Colon use in docstring in arguments blocks now formatted correctly.
Change argument detection to last colon in line.
Added support for "Reference" as a block header.
Convert quote block to admonition blocks
Added Github admonition quote block support.
Added start line anchor to regex
Changed "```" code snippet boundary detection from startswith to regex to prevent false positives.

Rework docstring markdown render. Solves issue #80
Improved whitespace and newline rendering.
Accepts more native markdown syntax without garbling render.
Solves Issue #82

Enumerate the docstring to detect end of docstring to appropriately close literal blocks, doctest and code blocks

Update literal blocks logic and format.
Syntax is same as reStructured text

* Render class __init__ method as constructor using class name

* Support including private modules with, aka files with "_" prefix.

Add private_modules arg

* Add table of contents feature to module file

* Fixed incorrect and unsafe src href link

* Added feature for user override of url line anchor notation (#74)

* Forced generated markdown file to be platform independent

* Crude workaround for AttributeError, no attribute "__create_fn__" (#72)

Observed in python 3.8, constructor for dataclasses had different function signature

* Added rendering support for enum, dataclass, and exception

* Updated API document example and bump version to 0.6.0